/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.Juego;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import modelo.Carta;
import modelo.Nivel;
/**
 *
 * @author norki
 */
public class FrmIntermedio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmIntermedio.class.getName());

  
    private controlador.Juego juego;
    private javax.swing.Timer timerCronometro;
    private javax.swing.JButton[][] botones;

    public FrmIntermedio() {
        initComponents();
        this.setLocationRelativeTo(null);
        juego = new controlador.Juego(modelo.Nivel.INTERMEDIO);
        juego.iniciarPartida();
         asignarBotones();
        actualizarTablero();
        actualizarInformacionJuego();
         iniciarTimerCronometro();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        PanelTablero = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        lblPuntaje = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();
        lblParejas = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        lblNivelActual = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        btnCambiarNivel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        PanelTablero.setBackground(new java.awt.Color(255, 204, 204));
        PanelTablero.setPreferredSize(new java.awt.Dimension(360, 320));
        PanelTablero.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

        jButton1.setText("jButton1");
        PanelTablero.add(jButton1);

        jButton2.setText("jButton2");
        PanelTablero.add(jButton2);

        jButton3.setText("jButton3");
        PanelTablero.add(jButton3);

        jButton4.setText("jButton4");
        PanelTablero.add(jButton4);

        jButton5.setText("jButton5");
        PanelTablero.add(jButton5);

        jButton6.setText("jButton6");
        PanelTablero.add(jButton6);

        jButton7.setText("jButton7");
        PanelTablero.add(jButton7);

        jButton8.setText("jButton8");
        PanelTablero.add(jButton8);

        jButton9.setText("jButton9");
        PanelTablero.add(jButton9);

        jButton10.setText("jButton10");
        PanelTablero.add(jButton10);

        jButton11.setText("jButton11");
        PanelTablero.add(jButton11);

        jButton12.setText("jButton12");
        PanelTablero.add(jButton12);

        jButton13.setText("jButton13");
        PanelTablero.add(jButton13);

        jButton14.setText("jButton14");
        PanelTablero.add(jButton14);

        jButton15.setText("jButton15");
        PanelTablero.add(jButton15);

        jButton16.setText("jButton16");
        PanelTablero.add(jButton16);

        jButton17.setText("jButton17");
        PanelTablero.add(jButton17);

        jButton18.setText("jButton18");
        PanelTablero.add(jButton18);

        jButton19.setText("jButton19");
        PanelTablero.add(jButton19);

        jButton20.setText("jButton20");
        PanelTablero.add(jButton20);

        jButton21.setText("jButton21");
        PanelTablero.add(jButton21);

        jButton22.setText("jButton22");
        PanelTablero.add(jButton22);

        jButton23.setText("jButton23");
        PanelTablero.add(jButton23);

        jButton24.setText("jButton24");
        PanelTablero.add(jButton24);

        jButton25.setText("jButton25");
        PanelTablero.add(jButton25);

        jButton26.setText("jButton26");
        PanelTablero.add(jButton26);

        jButton27.setText("jButton27");
        PanelTablero.add(jButton27);

        jButton28.setText("jButton28");
        PanelTablero.add(jButton28);

        jButton29.setText("jButton29");
        PanelTablero.add(jButton29);

        jButton30.setText("jButton30");
        PanelTablero.add(jButton30);

        jButton31.setText("jButton31");
        PanelTablero.add(jButton31);

        jButton32.setText("jButton32");
        PanelTablero.add(jButton32);

        lblPuntaje.setBackground(new java.awt.Color(204, 204, 255));
        lblPuntaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPuntaje.setText("         Puntaje");
        lblPuntaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPuntaje.setOpaque(true);

        lblIntentos.setBackground(new java.awt.Color(204, 204, 255));
        lblIntentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIntentos.setText("          Intentos");
        lblIntentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblIntentos.setOpaque(true);

        lblParejas.setBackground(new java.awt.Color(204, 204, 255));
        lblParejas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParejas.setText("          Parejas");
        lblParejas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblParejas.setOpaque(true);

        lblTiempo.setBackground(new java.awt.Color(204, 204, 255));
        lblTiempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTiempo.setText("       Tiempo");
        lblTiempo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTiempo.setOpaque(true);

        lblNivelActual.setBackground(new java.awt.Color(204, 204, 255));
        lblNivelActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNivelActual.setText("Nivel: Intermedio ");
        lblNivelActual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNivelActual.setOpaque(true);

        btnReiniciar.setBackground(new java.awt.Color(204, 204, 255));
        btnReiniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReiniciar.setOpaque(true);
        btnReiniciar.addActionListener(this::btnReiniciarActionPerformed);

        btnCambiarNivel.setBackground(new java.awt.Color(204, 204, 255));
        btnCambiarNivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCambiarNivel.setText("Cambiar Nivel");
        btnCambiarNivel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCambiarNivel.setOpaque(true);
        btnCambiarNivel.addActionListener(this::btnCambiarNivelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNivelActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblParejas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiarNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblParejas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTiempo)
                        .addComponent(btnCambiarNivel)
                        .addComponent(btnReiniciar)
                        .addComponent(btnSalir))
                    .addComponent(lblNivelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
            "Deseas salir?", "Confirmar salida",
            JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Deseas reiniciar la partida actual?",
            "Reiniciar Juego",
            JOptionPane.YES_NO_OPTION);

    if (respuesta == JOptionPane.YES_OPTION) {
        if (timerCronometro != null) {
            timerCronometro.stop();
        }
        juego.iniciarPartida(); 
        actualizarTablero();
       actualizarInformacionJuego();
        iniciarTimerCronometro();
    }
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnCambiarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarNivelActionPerformed
       if (juego.juegoTerminado()) {
        timerCronometro.stop();
        new FrmSeleccionNivel().setVisible(true);
        dispose();
        return;
    }

    int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Deseas seguir con la partida actual?",
            "Cambiar nivel",
            JOptionPane.YES_NO_OPTION);

    if (respuesta == JOptionPane.NO_OPTION) {
        timerCronometro.stop();
        new FrmSeleccionNivel().setVisible(true);
        dispose();
    }
      
    }//GEN-LAST:event_btnCambiarNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmIntermedio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTablero;
    private javax.swing.JButton btnCambiarNivel;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblNivelActual;
    private javax.swing.JLabel lblParejas;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblTiempo;
    // End of variables declaration//GEN-END:variables
private void asignarBotones() {
       botones = new javax.swing.JButton[4][8];
        botones[0][0] = jButton1;
        botones[0][1] = jButton2;
        botones[0][2] = jButton3;
        botones[0][3] = jButton4;
        botones[0][4] = jButton5;
        botones[0][5] = jButton6;
        botones[0][6] = jButton7;
        botones[0][7] = jButton8;

        botones[1][0] = jButton9;
        botones[1][1] = jButton10;
        botones[1][2] = jButton11;
        botones[1][3] = jButton12;
        botones[1][4] = jButton13;
        botones[1][5] = jButton14;
        botones[1][6] = jButton15;
        botones[1][7] = jButton16;

        botones[2][0] = jButton17;
        botones[2][1] = jButton18;
        botones[2][2] = jButton19;
        botones[2][3] = jButton20;
        botones[2][4] = jButton21;
        botones[2][5] = jButton22;
        botones[2][6] = jButton23;
        botones[2][7] = jButton24;

        botones[3][0] = jButton25;
        botones[3][1] = jButton26;
        botones[3][2] = jButton27;
        botones[3][3] = jButton28;
        botones[3][4] = jButton29;
        botones[3][5] = jButton30;
        botones[3][6] = jButton31;
        botones[3][7] = jButton32;

        for (int f = 0; f < 4; f++) {
            for (int c = 0; c < 8; c++) {
                final int fila = f;
                final int columna = c;
                botones[f][c].addActionListener(e -> SeleccionarCarta(fila, columna));
            }
        }
    }

   private void SeleccionarCarta(int fila, int columna) {
    if (juego.isEsperandoComparacion()) {
        return; 
    }
    juego.seleccionarCarta(fila, columna);
    actualizarTablero();
    if (juego.isEsperandoComparacion()) {
        javax.swing.Timer timerEspera = new javax.swing.Timer(2000, e -> {
            juego.limpiarSeleccion(); 
            actualizarTablero();
            actualizarInformacionJuego();
        });
        timerEspera.setRepeats(false); 
        timerEspera.start();
    } else {
        actualizarInformacionJuego();
    }
}

    private void actualizarInformacionJuego() {
        lblPuntaje.setText("Puntaje: " + juego.getJugador().getPuntaje());
    lblIntentos.setText("Intentos: " + juego.getJugador().getIntentos());

    int parejasTotales = juego.getTablero().getNivel().getCantidadParejas();

    lblParejas.setText("Parejas: "
        + juego.getJugador().getParejasEncontradas()
        + "/" + parejasTotales);

    lblTiempo.setText("Tiempo: "
        + juego.getCronometro().obtenerTiempoFormateado());

    lblNivelActual.setText("Nivel: "
        + juego.getTablero().getNivel().name());
}
    
private void actualizarTablero() {
    int filas = juego.getTablero().getFilas();
    int columnas = juego.getTablero().getColumnas();

    for (int f = 0; f < filas; f++) {
        for (int c = 0; c < columnas; c++) {

            Carta carta = juego.getTablero().obtenerCarta(f, c);
            JButton boton = botones[f][c];

            if (carta.isEncontrada() || carta.isVisible()) {

                boton.setText(carta.getImagen());
                boton.setIcon(null);
                boton.setEnabled(!carta.isEncontrada());

            } else {

                boton.setText("");
                boton.setIcon(null);
                boton.setEnabled(true);
            }
        }
    }
}

           private void iniciarTimerCronometro() {
    timerCronometro = new javax.swing.Timer(1000, e -> {
        juego.getCronometro().incrementar();

        lblTiempo.setText("Tiempo: " 
            + juego.getCronometro().obtenerTiempoFormateado());

        if (juego.juegoTerminado()) {
            timerCronometro.stop();
            mostrarFinDeJuego();
        }
    });

    timerCronometro.start();
}
   private void mostrarFinDeJuego() {

    String mensaje = "¡Felicidades, completaste el juego!\n\n"
            + "Puntaje final: " + juego.getJugador().getPuntaje() + "\n"
            + "Intentos: " + juego.getJugador().getIntentos() + "\n"
            + "Tiempo: " + juego.getCronometro().obtenerTiempoFormateado();

    JOptionPane.showMessageDialog(this,
            mensaje,
            "Juego terminado",
            JOptionPane.INFORMATION_MESSAGE);

    FrmSeleccionNivel frm = new FrmSeleccionNivel();
    frm.setLocationRelativeTo(null);
    frm.setVisible(true);

    dispose();
}
}
