package vista;
import modelo.Nivel;
import modelo.Carta;
import controlador.Juego;
import javax.swing.JButton;
import javax.swing.Timer;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

public class FrmIntermedio extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmIntermedio.class.getName());

    private Nivel nivelActual;
    private Juego juego;
    private JButton[][] botones;
    private Timer timerCronometro;
    public FrmIntermedio(Nivel nivel) {
    this.getContentPane().setBackground(new java.awt.Color(68, 28, 28));
    initComponents();
   this.setLocationRelativeTo(null);
    this.getContentPane().setBackground(new java.awt.Color(68, 28, 28));

    this.nivelActual = nivel;
    juego = new Juego(nivel);
    juego.iniciarPartida();

    asignarBotones();
    lblNivelActual.setText("Nivel: " + nivel.name());
    actualizarTablero();
    actualizarInformacionJuego();
    iniciarTimerCronometro();
}

/**
 *
 * @author norki
 */

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuntaje = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();
        lblParejas = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        lblNivelActual = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        btnCambiarNivel = new javax.swing.JButton();
        PanelTablero = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        bntSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego Memoria");
        setBackground(new java.awt.Color(68, 28, 28));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        lblPuntaje.setBackground(new java.awt.Color(124, 28, 28));
        lblPuntaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPuntaje.setText("        Puntaje");
        lblPuntaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPuntaje.setFocusable(false);
        lblPuntaje.setOpaque(true);

        lblIntentos.setBackground(new java.awt.Color(124, 28, 28));
        lblIntentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIntentos.setText("       Intentos");
        lblIntentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblIntentos.setFocusable(false);
        lblIntentos.setOpaque(true);

        lblParejas.setBackground(new java.awt.Color(124, 28, 28));
        lblParejas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParejas.setText("        Parejas");
        lblParejas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblParejas.setFocusable(false);
        lblParejas.setOpaque(true);

        lblTiempo.setBackground(new java.awt.Color(124, 28, 28));
        lblTiempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTiempo.setText("       Tiempo");
        lblTiempo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTiempo.setFocusable(false);
        lblTiempo.setOpaque(true);

        lblNivelActual.setBackground(new java.awt.Color(124, 28, 28));
        lblNivelActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNivelActual.setText("Nivel: Principiante");
        lblNivelActual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNivelActual.setFocusable(false);
        lblNivelActual.setOpaque(true);

        btnReiniciar.setBackground(new java.awt.Color(124, 28, 28));
        btnReiniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReiniciar.setContentAreaFilled(false);
        btnReiniciar.setFocusPainted(false);
        btnReiniciar.setFocusable(false);
        btnReiniciar.setOpaque(true);
        btnReiniciar.addActionListener(this::btnReiniciarActionPerformed);

        btnCambiarNivel.setBackground(new java.awt.Color(124, 28, 28));
        btnCambiarNivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCambiarNivel.setText("Cambiar Nivel");
        btnCambiarNivel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCambiarNivel.setContentAreaFilled(false);
        btnCambiarNivel.setFocusPainted(false);
        btnCambiarNivel.setFocusable(false);
        btnCambiarNivel.setOpaque(true);
        btnCambiarNivel.addActionListener(this::btnCambiarNivelActionPerformed);

        PanelTablero.setBackground(new java.awt.Color(43, 0, 0));
        PanelTablero.setToolTipText("");
        PanelTablero.setPreferredSize(new java.awt.Dimension(360, 320));
        PanelTablero.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

        jButton1.setBackground(new java.awt.Color(124, 28, 28));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        PanelTablero.add(jButton1);

        jButton3.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton3);

        jButton4.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton4);

        jButton5.setBackground(new java.awt.Color(124, 28, 28));
        jButton5.addActionListener(this::jButton5ActionPerformed);
        PanelTablero.add(jButton5);

        jButton2.setBackground(new java.awt.Color(124, 28, 28));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        PanelTablero.add(jButton2);

        jButton6.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton6);

        jButton7.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton7);

        jButton8.setBackground(new java.awt.Color(124, 28, 28));
        jButton8.addActionListener(this::jButton8ActionPerformed);
        PanelTablero.add(jButton8);

        jButton9.setBackground(new java.awt.Color(124, 28, 28));
        jButton9.addActionListener(this::jButton9ActionPerformed);
        PanelTablero.add(jButton9);

        jButton10.setBackground(new java.awt.Color(124, 28, 28));
        jButton10.addActionListener(this::jButton10ActionPerformed);
        PanelTablero.add(jButton10);

        jButton11.setBackground(new java.awt.Color(124, 28, 28));
        jButton11.addActionListener(this::jButton11ActionPerformed);
        PanelTablero.add(jButton11);

        jButton12.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton12);

        jButton13.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton13);

        jButton14.setBackground(new java.awt.Color(124, 28, 28));
        jButton14.addActionListener(this::jButton14ActionPerformed);
        PanelTablero.add(jButton14);

        jButton15.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton15);

        jButton16.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton16);

        jButton17.setBackground(new java.awt.Color(124, 28, 28));
        jButton17.addActionListener(this::jButton17ActionPerformed);
        PanelTablero.add(jButton17);

        jButton18.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton18);

        jButton19.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton19);

        jButton20.setBackground(new java.awt.Color(124, 28, 28));
        jButton20.addActionListener(this::jButton20ActionPerformed);
        PanelTablero.add(jButton20);

        jButton21.setBackground(new java.awt.Color(124, 28, 28));
        jButton21.addActionListener(this::jButton21ActionPerformed);
        PanelTablero.add(jButton21);

        jButton22.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton22);

        jButton23.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton23);

        jButton24.setBackground(new java.awt.Color(124, 28, 28));
        jButton24.addActionListener(this::jButton24ActionPerformed);
        PanelTablero.add(jButton24);

        jButton25.setBackground(new java.awt.Color(124, 28, 28));
        jButton25.addActionListener(this::jButton25ActionPerformed);
        PanelTablero.add(jButton25);

        jButton26.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton26);

        jButton27.setBackground(new java.awt.Color(124, 28, 28));
        jButton27.addActionListener(this::jButton27ActionPerformed);
        PanelTablero.add(jButton27);

        jButton28.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton28);

        jButton29.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton29);

        jButton30.setBackground(new java.awt.Color(124, 28, 28));
        jButton30.addActionListener(this::jButton30ActionPerformed);
        PanelTablero.add(jButton30);

        jButton31.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton31);

        jButton32.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton32);

        bntSalir.setBackground(new java.awt.Color(124, 28, 28));
        bntSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntSalir.setText("Salir");
        bntSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntSalir.setContentAreaFilled(false);
        bntSalir.setFocusPainted(false);
        bntSalir.setFocusable(false);
        bntSalir.setOpaque(true);
        bntSalir.addActionListener(this::bntSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNivelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarNivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParejas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNivelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblParejas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCambiarNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
       juego.reiniciarPartida();
    actualizarTablero(); 
    actualizarInformacionJuego();
    iniciarTimerCronometro();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnCambiarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarNivelActionPerformed
  if (juego.juegoTerminado()) {
        timerCronometro.stop();
        new FrmSeleccionNivel().setVisible(true);
        dispose();
        return;
    }

    int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Deseas seguir con la partida actual?",
            "Cambiar nivel",
            JOptionPane.YES_NO_OPTION);

    if (respuesta == JOptionPane.NO_OPTION) {
        timerCronometro.stop();
        new FrmSeleccionNivel().setVisible(true);
        dispose();
    }
    }//GEN-LAST:event_btnCambiarNivelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void bntSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalirActionPerformed
                                      
        int respuesta = JOptionPane.showConfirmDialog(this,
            "Deseas salir?", "Confirmar salida",
            JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_bntSalirActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> new FrmIntermedio(Nivel.INTERMEDIO).setVisible(true));
        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTablero;
    private javax.swing.JButton bntSalir;
    private javax.swing.JButton btnCambiarNivel;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblNivelActual;
    private javax.swing.JLabel lblParejas;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblTiempo;
    // End of variables declaration//GEN-END:variables

    private void asignarBotones() {
 botones = new javax.swing.JButton[4][8];
        botones[0][0] = jButton1;
        botones[0][1] = jButton2;
        botones[0][2] = jButton3;
        botones[0][3] = jButton4;
        botones[0][4] = jButton5;
        botones[0][5] = jButton6;
        botones[0][6] = jButton7;
        botones[0][7] = jButton8;

        botones[1][0] = jButton9;
        botones[1][1] = jButton10;
        botones[1][2] = jButton11;
        botones[1][3] = jButton12;
        botones[1][4] = jButton13;
        botones[1][5] = jButton14;
        botones[1][6] = jButton15;
        botones[1][7] = jButton16;

        botones[2][0] = jButton17;
        botones[2][1] = jButton18;
        botones[2][2] = jButton19;
        botones[2][3] = jButton20;
        botones[2][4] = jButton21;
        botones[2][5] = jButton22;
        botones[2][6] = jButton23;
        botones[2][7] = jButton24;

        botones[3][0] = jButton25;
        botones[3][1] = jButton26;
        botones[3][2] = jButton27;
        botones[3][3] = jButton28;
        botones[3][4] = jButton29;
        botones[3][5] = jButton30;
        botones[3][6] = jButton31;
        botones[3][7] = jButton32;
   for (int f = 0; f < 4; f++) {
    for (int c = 0; c < 8; c++) {
        final int fila = f;
        final int columna = c;
        botones[f][c].addActionListener(e -> SeleccionarCarta(fila, columna));
        }
    }
}
    private void SeleccionarCarta(int fila, int columna) {
    System.out.println("Click en fila: " + fila + " columna: " + columna);
    if (juego.isEsperandoComparacion()) {
        return; 
    }

    juego.seleccionarCarta(fila, columna);
    actualizarTablero();
    if (juego.isEsperandoComparacion()) {
        Timer timerEspera = new Timer(2000, e -> {
            juego.limpiarSeleccion(); 
            actualizarTablero();
            actualizarInformacionJuego();
        });
        timerEspera.setRepeats(false); 
        timerEspera.start();
    } else {
        actualizarInformacionJuego();
    }
}
    private void actualizarInformacionJuego() {
    lblPuntaje.setText("Puntaje: " + juego.getJugador().getPuntaje());
    lblIntentos.setText("Intentos: " + juego.getJugador().getIntentos());
    lblParejas.setText("Parejas: " + juego.getJugador().getParejasEncontradas());
    lblTiempo.setText("Tiempo: " + juego.getCronometro().obtenerTiempoFormateado());
}

private void actualizarTablero() {
    int filas = juego.getTablero().getFilas();
    int columnas = juego.getTablero().getColumnas();

    for (int f = 0; f < filas; f++) {
        for (int c = 0; c < columnas; c++) {

            Carta carta = juego.getTablero().obtenerCarta(f, c);
            JButton boton = botones[f][c];

            if (carta.isEncontrada() || carta.isVisible()) {
                java.net.URL imgURL = getClass().getResource("/vista/" + carta.getImagen());
                ImageIcon iconoOriginal = new ImageIcon(imgURL);
                java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(boton.getWidth() > 0 ? boton.getWidth() : 80, boton.getHeight() > 0 ? boton.getHeight() : 80, java.awt.Image.SCALE_SMOOTH);
                
                boton.setIcon(new ImageIcon(imagenEscalada));
                boton.setText("");
                boton.setEnabled(!carta.isEncontrada());

            } else {
                boton.setText("");
                boton.setIcon(null);
                boton.setEnabled(true);
            }
        }
    }
}


private void iniciarTimerCronometro() {
    if (timerCronometro != null) {
        timerCronometro.stop();
    }

    timerCronometro = new Timer(1000, e -> {
        juego.getCronometro().incrementar();
        lblTiempo.setText("Tiempo: " + juego.getCronometro().obtenerTiempoFormateado());

        if (juego.juegoTerminado()) {
            timerCronometro.stop();
            mostrarFinDeJuego();
        }
    });
    timerCronometro.start();
}

private void mostrarFinDeJuego() {

    String mensaje = "¡Felicidades, completaste el juego!\n\n"
            + "Puntaje final: " + juego.getJugador().getPuntaje() + "\n"
            + "Intentos: " + juego.getJugador().getIntentos() + "\n"
            + "Tiempo: " + juego.getCronometro().obtenerTiempoFormateado();

    JOptionPane.showMessageDialog(this,
            mensaje,
            "Juego terminado",
            JOptionPane.INFORMATION_MESSAGE);

    FrmSeleccionNivel frm = new FrmSeleccionNivel();
    frm.setLocationRelativeTo(null);
    frm.setVisible(true);

    dispose();
}
} 

