/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Nivel;
import modelo.Carta;
import controlador.Juego;
import javax.swing.JButton;
import javax.swing.Timer;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 
 */
public class FrmPrincipiante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipiante.class.getName());

    /**
     * Creates new form FrmPrincipiante
     */
    private Nivel nivelActual;
    private Juego juego;
    private JButton[][] botones;
    private Timer timerCronometro;
    public FrmPrincipiante(Nivel nivel) {
    initComponents();
    this.nivelActual = nivel;
    juego = new Juego(nivel);
    juego.iniciarPartida();
    inicializarMatrizBotones();
    lblNivelActual.setText("Nivel: " + nivel.name());
    actualizarTablero();
    actualizarEtiquetas();
    iniciarTimerCronometro();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuntaje = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();
        lblParejas = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        lblNivelActual = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        btnCambiarNivel = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        PanelTablero = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego Memoria");
        setResizable(false);

        lblPuntaje.setBackground(new java.awt.Color(204, 204, 255));
        lblPuntaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPuntaje.setText("         Puntaje");
        lblPuntaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPuntaje.setOpaque(true);

        lblIntentos.setBackground(new java.awt.Color(204, 204, 255));
        lblIntentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIntentos.setText("          Intentos");
        lblIntentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblIntentos.setOpaque(true);

        lblParejas.setBackground(new java.awt.Color(204, 204, 255));
        lblParejas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParejas.setText("          Parejas");
        lblParejas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblParejas.setOpaque(true);

        lblTiempo.setBackground(new java.awt.Color(204, 204, 255));
        lblTiempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTiempo.setText("       Tiempo");
        lblTiempo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTiempo.setOpaque(true);

        lblNivelActual.setBackground(new java.awt.Color(204, 204, 255));
        lblNivelActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNivelActual.setText("Nivel: Principiante");
        lblNivelActual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNivelActual.setOpaque(true);

        btnReiniciar.setBackground(new java.awt.Color(204, 204, 255));
        btnReiniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReiniciar.setOpaque(true);
        btnReiniciar.addActionListener(this::btnReiniciarActionPerformed);

        btnCambiarNivel.setBackground(new java.awt.Color(204, 204, 255));
        btnCambiarNivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCambiarNivel.setText("Cambiar Nivel");
        btnCambiarNivel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCambiarNivel.setOpaque(true);
        btnCambiarNivel.addActionListener(this::btnCambiarNivelActionPerformed);

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        PanelTablero.setBackground(new java.awt.Color(255, 204, 204));
        PanelTablero.setPreferredSize(new java.awt.Dimension(360, 320));
        PanelTablero.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

        jButton1.setText("jButton1");
        PanelTablero.add(jButton1);

        jButton2.setText("jButton2");
        PanelTablero.add(jButton2);

        jButton3.setText("jButton3");
        PanelTablero.add(jButton3);

        jButton4.setText("jButton4");
        PanelTablero.add(jButton4);

        jButton5.setText("jButton5");
        PanelTablero.add(jButton5);

        jButton6.setText("jButton6");
        PanelTablero.add(jButton6);

        jButton7.setText("jButton7");
        PanelTablero.add(jButton7);

        jButton8.setText("jButton8");
        PanelTablero.add(jButton8);

        jButton9.setText("jButton9");
        PanelTablero.add(jButton9);

        jButton10.setText("jButton10");
        PanelTablero.add(jButton10);

        jButton11.setText("jButton11");
        PanelTablero.add(jButton11);

        jButton12.setText("jButton12");
        PanelTablero.add(jButton12);

        jButton13.setText("jButton13");
        PanelTablero.add(jButton13);

        jButton14.setText("jButton14");
        PanelTablero.add(jButton14);

        jButton15.setText("jButton15");
        PanelTablero.add(jButton15);

        jButton16.setText("jButton16");
        PanelTablero.add(jButton16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNivelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblParejas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCambiarNivel)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParejas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTiempo)
                    .addComponent(btnReiniciar)
                    .addComponent(btnCambiarNivel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnSalir)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
       juego.reiniciarPartida();
    actualizarTablero(); 
    actualizarEtiquetas();
    iniciarTimerCronometro();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
        "Deseas salir?", "Confirmar salida",
        JOptionPane.YES_NO_OPTION);
    if (respuesta == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCambiarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarNivelActionPerformed
      if (timerCronometro != null) {
        timerCronometro.stop();
    }
    
    
    FrmSeleccionNivel seleccion = new FrmSeleccionNivel();
    seleccion.setLocationRelativeTo(null); 
    seleccion.setVisible(true);
    
   
    this.dispose();
    }//GEN-LAST:event_btnCambiarNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipiante(Nivel.PRINCIPIANTE).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTablero;
    private javax.swing.JButton btnCambiarNivel;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblNivelActual;
    private javax.swing.JLabel lblParejas;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblTiempo;
    // End of variables declaration//GEN-END:variables




private void actualizarTablero() {
    int filas = juego.getTablero().getFilas();
    int columnas = juego.getTablero().getColumnas();

    for (int f = 0; f < filas; f++) {
        for (int c = 0; c < columnas; c++) {

            Carta carta = juego.getTablero().obtenerCarta(f, c);
            JButton boton = botones[f][c];

            if (carta.isEncontrada() || carta.isVisible()) {

                boton.setText(carta.getImagen());
                boton.setIcon(null);
                boton.setEnabled(!carta.isEncontrada());

            } else {       
    boton.setText(boton.getName());
    boton.setIcon(null);
    boton.setEnabled(true);
            }
        }
    }
}
   
private void actualizarEtiquetas() {
    lblPuntaje.setText("Puntaje: " + juego.getJugador().getPuntaje());
    lblIntentos.setText("Intentos: " + juego.getJugador().getIntentos());
    lblParejas.setText("Parejas: " + juego.getJugador().getParejasEncontradas());
    lblTiempo.setText("Tiempo: " + juego.getCronometro().obtenerTiempoFormateado());
}

private void iniciarTimerCronometro() {
    if (timerCronometro != null) {
        timerCronometro.stop();
    }

    timerCronometro = new Timer(1000, e -> {
        juego.getCronometro().incrementar();
        lblTiempo.setText("Tiempo: " + juego.getCronometro().obtenerTiempoFormateado());

        if (juego.juegoTerminado()) {
            timerCronometro.stop();
            mostrarFinDeJuego();
        }
    });
    timerCronometro.start();
}

private void mostrarFinDeJuego() {
    String mensaje = "¡Felicidades, completaste el juego!\n\n"
            + "Puntaje final: " + juego.getJugador().getPuntaje() + "\n"
            + "Intentos: " + juego.getJugador().getIntentos() + "\n"
            + "Tiempo: " + juego.getCronometro().obtenerTiempoFormateado();

    JOptionPane.showMessageDialog(this, mensaje, "Juego terminado",
            JOptionPane.INFORMATION_MESSAGE);
}
private void inicializarMatrizBotones() {
    botones = new JButton[4][4];
    botones[0][0] = jButton1;
    botones[0][1] = jButton2;
    botones[0][2] = jButton3;
    botones[0][3] = jButton4;
    botones[1][0] = jButton5;
    botones[1][1] = jButton6;
    botones[1][2] = jButton7;
    botones[1][3] = jButton8;
    botones[2][0] = jButton9;
    botones[2][1] = jButton10;
    botones[2][2] = jButton11;
    botones[2][3] = jButton12;
    botones[3][0] = jButton13;
    botones[3][1] = jButton14;
    botones[3][2] = jButton15;
    botones[3][3] = jButton16;
   for (int f = 0; f < 4; f++) {
        for (int c = 0; c < 4; c++) {
            final int fila = f;
            final int columna = c;

            botones[f][c].addActionListener(e -> manejarClickCarta(fila, columna));
        }
    }
}

private void manejarClickCarta(int fila, int columna) {
    System.out.println("Click en fila: " + fila + " columna: " + columna);
    if (juego.isEsperandoComparacion()) {
        return; 
    }

    juego.seleccionarCarta(fila, columna);
    actualizarTablero();
    if (juego.isEsperandoComparacion()) {
        Timer timerEspera = new Timer(2000, e -> {
            juego.limpiarSeleccion(); 
            actualizarTablero();
            actualizarEtiquetas();
        });
        timerEspera.setRepeats(false); 
        timerEspera.start();
    } else {
        actualizarEtiquetas();
    }
}

}
