/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Nivel;
import modelo.Carta;
import controlador.Juego;
import javax.swing.JButton;
import javax.swing.Timer;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 
 */
public class FrmPrincipiante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipiante.class.getName());

    /**
     * Creates new form FrmPrincipiante
     */
    private Nivel nivelActual;
    private Juego juego;
    private JButton[][] botones;
    private Timer timerCronometro;
    public FrmPrincipiante(Nivel nivel) {
    this.getContentPane().setBackground(new java.awt.Color(68, 28, 28));
    initComponents();
    this.setLocationRelativeTo(null);
    this.nivelActual = nivel;
    juego = new Juego(nivel);
    juego.iniciarPartida();
    asignarBotones();
    lblNivelActual.setText("Nivel: " + nivel.name());
    actualizarTablero();
    actualizarInformacionJuego();
    iniciarTimerCronometro();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuntaje = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();
        lblParejas = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        lblNivelActual = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        btnCambiarNivel = new javax.swing.JButton();
        PanelTablero = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        bntSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego Memoria");
        setBackground(new java.awt.Color(68, 28, 28));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        lblPuntaje.setBackground(new java.awt.Color(124, 28, 28));
        lblPuntaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPuntaje.setText("        Puntaje");
        lblPuntaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPuntaje.setFocusable(false);
        lblPuntaje.setOpaque(true);

        lblIntentos.setBackground(new java.awt.Color(124, 28, 28));
        lblIntentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIntentos.setText("       Intentos");
        lblIntentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblIntentos.setFocusable(false);
        lblIntentos.setOpaque(true);

        lblParejas.setBackground(new java.awt.Color(124, 28, 28));
        lblParejas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParejas.setText("        Parejas");
        lblParejas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblParejas.setFocusable(false);
        lblParejas.setOpaque(true);

        lblTiempo.setBackground(new java.awt.Color(124, 28, 28));
        lblTiempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTiempo.setText("       Tiempo");
        lblTiempo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTiempo.setFocusable(false);
        lblTiempo.setOpaque(true);

        lblNivelActual.setBackground(new java.awt.Color(124, 28, 28));
        lblNivelActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNivelActual.setText("Nivel: Principiante");
        lblNivelActual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNivelActual.setFocusable(false);
        lblNivelActual.setOpaque(true);

        btnReiniciar.setBackground(new java.awt.Color(124, 28, 28));
        btnReiniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReiniciar.setContentAreaFilled(false);
        btnReiniciar.setFocusPainted(false);
        btnReiniciar.setFocusable(false);
        btnReiniciar.setOpaque(true);
        btnReiniciar.addActionListener(this::btnReiniciarActionPerformed);

        btnCambiarNivel.setBackground(new java.awt.Color(124, 28, 28));
        btnCambiarNivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCambiarNivel.setText("Cambiar Nivel");
        btnCambiarNivel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCambiarNivel.setContentAreaFilled(false);
        btnCambiarNivel.setFocusPainted(false);
        btnCambiarNivel.setFocusable(false);
        btnCambiarNivel.setOpaque(true);
        btnCambiarNivel.addActionListener(this::btnCambiarNivelActionPerformed);

        PanelTablero.setBackground(new java.awt.Color(43, 0, 0));
        PanelTablero.setToolTipText("");
        PanelTablero.setPreferredSize(new java.awt.Dimension(360, 320));
        PanelTablero.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

        jButton1.setBackground(new java.awt.Color(124, 28, 28));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        PanelTablero.add(jButton1);

        jButton3.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton3);

        jButton4.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton4);

        jButton5.setBackground(new java.awt.Color(124, 28, 28));
        jButton5.addActionListener(this::jButton5ActionPerformed);
        PanelTablero.add(jButton5);

        jButton2.setBackground(new java.awt.Color(124, 28, 28));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        PanelTablero.add(jButton2);

        jButton6.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton6);

        jButton7.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton7);

        jButton8.setBackground(new java.awt.Color(124, 28, 28));
        jButton8.addActionListener(this::jButton8ActionPerformed);
        PanelTablero.add(jButton8);

        jButton9.setBackground(new java.awt.Color(124, 28, 28));
        jButton9.addActionListener(this::jButton9ActionPerformed);
        PanelTablero.add(jButton9);

        jButton10.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton10);

        jButton11.setBackground(new java.awt.Color(124, 28, 28));
        jButton11.addActionListener(this::jButton11ActionPerformed);
        PanelTablero.add(jButton11);

        jButton12.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton12);

        jButton13.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton13);

        jButton14.setBackground(new java.awt.Color(124, 28, 28));
        jButton14.addActionListener(this::jButton14ActionPerformed);
        PanelTablero.add(jButton14);

        jButton15.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton15);

        jButton16.setBackground(new java.awt.Color(124, 28, 28));
        PanelTablero.add(jButton16);

        bntSalir.setBackground(new java.awt.Color(124, 28, 28));
        bntSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntSalir.setText("Salir");
        bntSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntSalir.setContentAreaFilled(false);
        bntSalir.setFocusPainted(false);
        bntSalir.setFocusable(false);
        bntSalir.setOpaque(true);
        bntSalir.addActionListener(this::bntSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNivelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParejas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarNivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNivelActual)
                        .addGap(18, 18, 18)
                        .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIntentos)
                        .addGap(18, 18, 18)
                        .addComponent(lblParejas)
                        .addGap(18, 18, 18)
                        .addComponent(lblTiempo)
                        .addGap(18, 18, 18)
                        .addComponent(btnReiniciar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCambiarNivel)
                        .addGap(18, 18, 18)
                        .addComponent(bntSalir)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
       juego.reiniciarPartida();
    actualizarTablero(); 
    actualizarInformacionJuego();
    iniciarTimerCronometro();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnCambiarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarNivelActionPerformed
  if (juego.juegoTerminado()) {
        timerCronometro.stop();
        new FrmSeleccionNivel().setVisible(true);
        dispose();
        return;
    }

    int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Deseas seguir con la partida actual?",
            "Cambiar nivel",
            JOptionPane.YES_NO_OPTION);

    if (respuesta == JOptionPane.NO_OPTION) {
        timerCronometro.stop();
        new FrmSeleccionNivel().setVisible(true);
        dispose();
    }
    }//GEN-LAST:event_btnCambiarNivelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void bntSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalirActionPerformed
                                      
        int respuesta = JOptionPane.showConfirmDialog(this,
            "Deseas salir?", "Confirmar salida",
            JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_bntSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipiante(Nivel.PRINCIPIANTE).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTablero;
    private javax.swing.JButton bntSalir;
    private javax.swing.JButton btnCambiarNivel;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblNivelActual;
    private javax.swing.JLabel lblParejas;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblTiempo;
    // End of variables declaration//GEN-END:variables

    private void asignarBotones() {
    botones = new JButton[4][4];
    botones[0][0] = jButton1;
    botones[0][1] = jButton2;
    botones[0][2] = jButton3;
    botones[0][3] = jButton4;
    botones[1][0] = jButton5;
    botones[1][1] = jButton6;
    botones[1][2] = jButton7;
    botones[1][3] = jButton8;
    botones[2][0] = jButton9;
    botones[2][1] = jButton10;
    botones[2][2] = jButton11;
    botones[2][3] = jButton12;
    botones[3][0] = jButton13;
    botones[3][1] = jButton14;
    botones[3][2] = jButton15;
    botones[3][3] = jButton16;
   for (int f = 0; f < 4; f++) {
        for (int c = 0; c < 4; c++) {
            final int fila = f;
            final int columna = c;

            botones[f][c].addActionListener(e -> SeleccionarCarta(fila, columna));
        }
    }
}
    private void SeleccionarCarta(int fila, int columna) {
    System.out.println("Click en fila: " + fila + " columna: " + columna);
    if (juego.isEsperandoComparacion()) {
        return; 
    }

    juego.seleccionarCarta(fila, columna);
    actualizarTablero();
    if (juego.isEsperandoComparacion()) {
        Timer timerEspera = new Timer(2000, e -> {
            juego.limpiarSeleccion(); 
            actualizarTablero();
            actualizarInformacionJuego();
        });
        timerEspera.setRepeats(false); 
        timerEspera.start();
    } else {
        actualizarInformacionJuego();
    }
}
    private void actualizarInformacionJuego() {
    lblPuntaje.setText("Puntaje: " + juego.getJugador().getPuntaje());
    lblIntentos.setText("Intentos: " + juego.getJugador().getIntentos());
    lblParejas.setText("Parejas: " + juego.getJugador().getParejasEncontradas());
    lblTiempo.setText("Tiempo: " + juego.getCronometro().obtenerTiempoFormateado());
}

private void actualizarTablero() {
    int filas = juego.getTablero().getFilas();
    int columnas = juego.getTablero().getColumnas();

    for (int f = 0; f < filas; f++) {
        for (int c = 0; c < columnas; c++) {

            Carta carta = juego.getTablero().obtenerCarta(f, c);
            JButton boton = botones[f][c];

            if (carta.isEncontrada() || carta.isVisible()) {
                java.net.URL imgURL = getClass().getResource("/vista/" + carta.getImagen());
                ImageIcon iconoOriginal = new ImageIcon(imgURL);
                java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(boton.getWidth() > 0 ? boton.getWidth() : 80, boton.getHeight() > 0 ? boton.getHeight() : 80, java.awt.Image.SCALE_SMOOTH);
                
                boton.setIcon(new ImageIcon(imagenEscalada));
                boton.setText("");
                boton.setEnabled(!carta.isEncontrada());

            } else {
                boton.setText("");
                boton.setIcon(null);
                boton.setEnabled(true);
            }
        }
    }
}


private void iniciarTimerCronometro() {
    if (timerCronometro != null) {
        timerCronometro.stop();
    }

    timerCronometro = new Timer(1000, e -> {
        juego.getCronometro().incrementar();
        lblTiempo.setText("Tiempo: " + juego.getCronometro().obtenerTiempoFormateado());

        if (juego.juegoTerminado()) {
            timerCronometro.stop();
            mostrarFinDeJuego();
        }
    });
    timerCronometro.start();
}

private void mostrarFinDeJuego() {

    String mensaje = "¡Felicidades, completaste el juego!\n\n"
            + "Puntaje final: " + juego.getJugador().getPuntaje() + "\n"
            + "Intentos: " + juego.getJugador().getIntentos() + "\n"
            + "Tiempo: " + juego.getCronometro().obtenerTiempoFormateado();

    JOptionPane.showMessageDialog(this,
            mensaje,
            "Juego terminado",
            JOptionPane.INFORMATION_MESSAGE);

    FrmSeleccionNivel frm = new FrmSeleccionNivel();
    frm.setLocationRelativeTo(null);
    frm.setVisible(true);

    dispose();
}
} 

