/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Nivel;


/**
 *
 * @author María J
 */
public class FrmSeleccionNivel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSeleccionNivel.class.getName());

    /**
     * Creates new form FrmJuego
     */
    public FrmSeleccionNivel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSeleccionNivel = new javax.swing.JLabel();
        btnPrincipiante = new javax.swing.JButton();
        btnIntermedio = new javax.swing.JButton();
        btnAvanzado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego Memoria");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSeleccionNivel.setBackground(new java.awt.Color(153, 153, 255));
        lblSeleccionNivel.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        lblSeleccionNivel.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionNivel.setText(" ¿Qué nivel quieres jugar?");
        jPanel1.add(lblSeleccionNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 340, 37));

        btnPrincipiante.setBackground(new java.awt.Color(204, 153, 255));
        btnPrincipiante.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnPrincipiante.setText("Principiante");
        btnPrincipiante.setBorder(null);
        btnPrincipiante.addActionListener(this::btnPrincipianteActionPerformed);
        jPanel1.add(btnPrincipiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 170, 50));

        btnIntermedio.setBackground(new java.awt.Color(204, 153, 255));
        btnIntermedio.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnIntermedio.setText("Intermedio");
        btnIntermedio.setBorder(null);
        btnIntermedio.addActionListener(this::btnIntermedioActionPerformed);
        jPanel1.add(btnIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 170, 50));

        btnAvanzado.setBackground(new java.awt.Color(204, 153, 255));
        btnAvanzado.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnAvanzado.setText("Avanzado");
        btnAvanzado.setBorder(null);
        btnAvanzado.addActionListener(this::btnAvanzadoActionPerformed);
        jPanel1.add(btnAvanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 170, 50));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -4, 880, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipianteActionPerformed
      FrmPrincipiante juego = new FrmPrincipiante(Nivel.PRINCIPIANTE);
    juego.setLocationRelativeTo(null);
    juego.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnPrincipianteActionPerformed

    private void btnAvanzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzadoActionPerformed
FrmAvanzado juego = new FrmAvanzado();
    juego.setLocationRelativeTo(null);
    juego.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnAvanzadoActionPerformed

    private void btnIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntermedioActionPerformed
       FrmIntermedio juego = new FrmIntermedio(Nivel.INTERMEDIO);
       juego.setLocationRelativeTo(null);
juego.setVisible(true);
dispose();
    
    juego.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIntermedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSeleccionNivel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzado;
    private javax.swing.JButton btnIntermedio;
    private javax.swing.JButton btnPrincipiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSeleccionNivel;
    // End of variables declaration//GEN-END:variables
}
